### ISSUE TITLE
Feature request: version information

### ISSUE THREAD

**Issue by shaze** [Parsoa/SVDSS#11]
Would it be possible to include an option on SVDSS like `--version` so that it prints out its current version. This would be very useful in developing reproducible pipelines

Thanks

**Comment by ldenti** [comment]
Hi, yeah, that's a reasonable addition. Thanks for asking for it :)

See my last commit (415b72e). Now if you run:
```
SVDSS --version
```
you'll get
```
SVDSS, Structural Variant Discovery from Sample-specific Strings.     # this to stderr
SVDSS, v1.0.3                                                         # this to stdout
```

I'll draft a new release when I'll have solved the two remaining issues.

Best,
Luca

**Comment by ldenti** [comment]
Closing.
