### ISSUE TITLE
About Extend Tier 2

### ISSUE THREAD

**Issue by songbowang125** [Parsoa/SVDSS#15]
Hi, I am reading your paper recently published online in Nature Methods. You provided a wonderful job on hard-to-call SV detection with a novel framework. However, I got some confusions about the Extend Tier 2 benchmarking.

1. NIST_SVs_Integration_v0.6 FTP only provides a bed file for Tier 2 (HG002_SVs_Tier2_v0.6.bed). There is no Tier 2 VCF file so that Truvari is not applicable (You mentioned Truvari command in page xvi of supplementary file. Truvari requires both VCF file and included bed file).  So you used another comparison tool (maybe bedtools intersection) for Tier 2? 

2. Could you please provide the details of Extend Tier 2? I didn't find the Extend Tier 2 file in your supplementary files and githubs. Extend Tier 2 played a key role in your benchmarking section and was much helpful for readers to run some tests or futher comparison.

Thanks

**Comment by ldenti** [comment]
Hi, thanks!

For extended tier 2, you are right, there is no .bed in the FTP server but we built it from Tier1 .bed using `bedtools`: extended Tier 2 is everything outside Tier 1, so we computed it by complementing the Tier1 .bed.

You can find all the steps to reproduce our exps here: https://github.com/ldenti/svdss-experiments:
* here for hg38: https://github.com/ldenti/svdss-experiments#prerequisites
```
wget https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/HG002_SVs_Tier1_v0.6.bed
sed -e 's/^/chr/' HG002_SVs_Tier1_v0.6.bed > Tier1_v0.6.hg19.bed
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/liftOver
chmod +x liftOver
wget http://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz
gunzip hg19ToHg38.over.chain.gz
./liftOver Tier1_v0.6.hg19.bed hg19ToHg38.over.chain Tier1_v0.6.hg38.bed Tier1_v0.6.unlifted.bed
for c in $(seq 1 22) X Y ; do grep -P "^chr${c}\t" Tier1_v0.6.hg38.bed ; done | sort -k1,1 -k2,2n > Tier1_v0.6.hg38.noalt.bed
bedtools complement -i Tier1_v0.6.hg38.noalt.bed -g hg38.chroms.genome > Tier23_v0.6.hg38.noalt.bed
```
* here for hg19: https://github.com/ldenti/svdss-experiments#giab-vs-dipcall-analysis
```
wget https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/NIST_SVs_Integration_v0.6/HG002_SVs_Tier1_v0.6.bed
bedtools complement -i HG002_SVs_Tier1_v0.6.bed -g hs37d5.chroms.fa.fai > HG002_SVs_Tier23_v0.6.bed
```
But I just realized that this is a bit hidden in the README.. And moreover I named the Extended Tier 2 .bed file as Tier23.. I'll write a section for it to better explain everything.

Let me know if this helps you out.

Best,

**Comment by ldenti** [comment]
I tried to make it clearer in the README of that repo ([here](https://github.com/ldenti/svdss-experiments#tiers) and [here](https://github.com/ldenti/svdss-experiments#giab-vs-dipcall-analysis)).

**Comment by songbowang125** [comment]
oh, that really helps. I will do more tests. Thanks

**Comment by ldenti** [comment]
I'm closing this issue for now, if you have any other doubt/question on this, please reopen it.
