### ISSUE TITLE
Segmentation fault while calling SV using --clipped option (v1.0.5)

### ISSUE THREAD

**Issue by arnav26** [Parsoa/SVDSS#24]
Hello,

While calling SV using clipped option, I get Seg fault (core dumped) message. This only happens if I use the --clipped flags. I have tried this on different samples but the error happens always after the same line (predicting deletions...).  Without --clipped option, the program finishes correctly.

Here is the call command I use.

`SVDSS call --bam ESWxAlpen_male_RS/smoothed.selective.bam --workdir ESWxAlpen_male_RS/ --reference Sus_scrofa.Sscrofa11.1.dna.toplevel.fa --batches 15 --threads 50 --clipped --min-cluster-weight 2
`

and the log 
"
SVDSS, Structural Variant Discovery from Sample-specific Strings.
Mode: call
[I] ESWxAlpen_male_RS/ 
[I] PingPong SV Caller running on 50 threads.. 
[I] Loading reference genome from Sus_scrofa.Sscrofa11.1.dna.toplevel.fa.. 
...
[I] Loaded all chromosomes. 
[I] Loading assmbled SFS.. 
[I] Loaded 5568466 SFS strings on 1843437 reads. 
[I] Extending superstrings on 50 threads.. 
[I] Processed batch 184. Alignments so far: 1840000. Alignments per second: 19784. Time: 93
[I] Done. 
[I] Extension complete. 617482  clipped SFS. 
[I] Maximum extended-SFS length: 18527 bp. Using separation distance 20379. 
[I] Retrieved 54474  intervals. 
[I] Flattening interval clusters.. 
[I] Analyzing 136331 clusters.. 
[I] Processed 119850 clusters so far. Clusters per second: 1933. Time: 62
[I] Calling SVs from 111023 clusters.. 
[I] 98427 SVs before chain filtering. 
[I] 98349 SVs after chain filtering. 
[I] Predicted 98349 SVs from extended SFS. 
[I] Outputting POA alignments to ESWxAlpen_male_RS//poa.sam.. 
[I] Exporting 98349 SV calls to ESWxAlpen_male_RS//svs_poa.vcf.. 
[I] Predicting SVS from 617482 clipped SFS on 50 threads.. 
[I] 309993 left clips. 
[I] 307489 right clips. 
[I] Preprocessing clipped SFS.. 
[I] 728 left clips. 
[I] 748 right clips. 
[I] Predicting insertions.. 
[I] Predicting deletions.. 
/cluster/shadow/.lsbatch/1690915686.263057233: line 8: 113819 Segmentation fault      (core dumped) SVDSS call --bam ESWxAlpen_male_RS/smoothed.selective.bam --workdir ESWxAlpen_male_RS/ --reference Sus_scrofa.Sscrofa11.1.dna.toplevel.fa --batches 15 --threads 50 --clipped --min-cluster-weight 2
"

Thanks!

**Comment by ldenti** [comment]
Hi,
indeed there was a bug. I fixed it in 6fa89f0a4f8ec03ab87c3eb8a3288a6b82214767 . Now I've able to call SVs from clipped reads.

However, I won't draft a new release and provide the conda package very soon. I'd suggest you to compile from source. But in the meantime I'll build the static binary so that if you encounter any problem during the compilation process, you can use that (but it may take some more time).

Let me know if you manage to run succesfully the fixed source code.

Finally, I'd like to note that the `--clipped` option is experimental and we didn't test it extensively.. So do not blindly trust its results.

**Comment by ldenti** [comment]
Well, it was faster than expected.. the static binary creation went flawlessly.. In case you need it, here the binary: [SVDSS_linux_x86-64.gz](https://github.com/Parsoa/SVDSS/files/12239366/SVDSS_linux_x86-64.gz)

Please, let me know if it works.

**Comment by arnav26** [comment]
I tried the static binary and it does work now.

Thanks a lot for the quick fix :)
