### ISSUE TITLE
Question about SFS extraction

### ISSUE THREAD

**Issue by LYC-vio** [Parsoa/SVDSS#25]
Hi,

To better understand the concept of SFS, I've created a tiny demo_ref.fa and demo_read.fa as below:

demo_ref.fa:
```
>read_1
AAAAAAAAAAAAAAAAAAAA
>read_2
AAAAAAAAAAAAAAAAAAAA
>read_3
AAAAAAAAAAAAAAAAAAAA
>read_4
AAAAAAAAAAAAAAAAAAAA
>read_5
AAAAAAAAAAAAAAAAAAAA
>read_6
AAAAAAAAAAAAAAAAAAAA
>read_7
AAAAAAAAAAAAAAAAAAAA
>read_8
AAAAAAAAAAAAAAAAAAAA
>read_9
AAAAAAAAAAAAAAAAAAAA
>read_10
AAAAAAAAAAAAAAAAAAAA
```
demo_read.fa:
```
>read_1
AAAATTTAAAAAAAAAAAAA
>read_2
AAAAAAAAAAAAAAAAAAAA
>read_3
AAAAAAAAAAAAAAAAAAAA
>read_4
AAAAAAAAAAAAAAAAAAAA
>read_5
AAAAATTTTAAAAAAAAAAA
>read_6
AAAAAAAAAAAAAAAAAAAA
>read_7
AAAAAAAAAAAAAAAAAAAA
>read_8
AAAAAAAAAGGAAAAAAAAA
>read_9
AAAAAAAAAAAAAAAAAAAA
>read_10
CCCCCCCATCGGGGCCCCCCCCCCCCCAAAAAAAAAAAAAAA
```
The sfs I got after SVDSS search was:
```
read_1  6       2       1       0
*       3       2       1       0
read_5  8       2       1       0
*       4       2       1       0
read_10 26      1       1       0
*       25      1       1       0
*       24      1       1       0
*       23      1       1       0
*       22      1       1       0
*       21      1       1       0
*       20      1       1       0
*       19      1       1       0
*       18      1       1       0
*       17      1       1       0
*       16      1       1       0
*       15      1       1       0
*       14      1       1       0
*       13      1       1       0
*       12      1       1       0
*       11      1       1       0
*       10      1       1       0
*       9       1       1       0
*       7       2       1       0
*       6       1       1       0
*       5       1       1       0
*       4       1       1       0
*       3       1       1       0
*       2       1       1       0
*       1       1       1       0
*       0       1       1       0
read_8  10      1       1       0
*       9       1       1       0
```

However, the SFS output was somehow different from my expectation. For example, in read_1, I would expect "AT", "TT" and  "TA" as SFSs, but it seems that SVDSS only chose "AT" and "TA" as SFSs. Additionally, there were multiple single-base SFSs in read 10, and they still presist even after I run SVDSS search with --assemble or run SVDSS assemble (the output was the same with the initial .sfs)

Have I misunderstood the definition of SFS? I know that this example is more or less an extreme case, but this kind of sequence could exist in homopolymer regions. Could you please clarify more about SVDSS's (or PingPong's) behavior in this kind of situation?

Thank you

Best

**Comment by ldenti** [comment]
Hi,
one thing to keep in mind is: while building the index from the reference, we consider the sequences and their reverse-and-complement.

So your index will have both `AAAAAAAAAAAAAAAAAAAA` and `TTTTTTTTTTTTTTTTTTTT`. Indeed, if you try to query `TTTTTTTTTTTTTTTTTTTT`, you don't get any SFS. But if you query `TTTTTTTTTTTTTTTTTTTTTTTTT` (5 T longer), you will get 5 SFSs that are 5 substrings of length 21 (the reference is 20T long).

This should explain why you don't have `TT` in the output. However, let me explain the algorithm using read_1 as an example:
1. the search start from the end of the query, a single `A` is found in the index. Search move backward, `AA` is still in the index.. This goes until you reach the first `T`. `TAAAAAAAAAAAAA` can not be found in the index. Hence the query restart from the `T` but this time forward: `T` is found. `TA` is not in the index, hence `TA` is a SFS. Search then restart backward from position left to the `A` (last char of the SFS), so the `T`.
2. `T` is found. `TT` is found, `TTT` is found. `ATTT` is not found. Then we proceed forward. `A` is found. `AT` is not found. Here the second SFS.

Here a visual representation (hope it's clear: o are matches, x are mismatches. - are the SFS)
```
AAAATTTAAAAAAAAAAAAA
      xooooooooooooo
      ox
      --
   xooo  
   ox
   --
oooo
```

We can follow the same algorithm for read 10. All the `C` can not be found in the index, hence each of them is specific - for this reason you have a lot of SFS of size 1. Same for the `G`:
```
CCCCCCCATCGGGGCCCCCCCCCCCCCAAAAAAAAAAAAAAA
                          xooooooooooooooo
                          x
                          -
                         x
                         -
                        x
                        -
...
          x
          -
         x
         -
       xo
       ox
       --
      xo
      x
      -
     x
     -
...
x
-
```

Let me know if this helps you out of if you have other doubts.

Best,

**Comment by LYC-vio** [comment]
This helps a lot! Really appreciate your explanation

Best
