### ISSUE TITLE
Index failing

### ISSUE THREAD

**Issue by aysegokce** [Parsoa/SVDSS#35]
Hello!
I am running svdss with HG002, which is aligned with this [reference](ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz). 
When I tried to index the reference, it throws the following error:

```
SVDSS index --reference hs37d5.fa.gz --index hs37d5.fmd
SVDSS, Structural Variant Discovery from Sample-specific Strings.
Mode: index
[I] . 
Please provide a FASTA/Q file. Halting..
```

I tried with the unzipped version, but there was still some error. It looks like the problem is with the reference. I wonder if there is any workaround for this step.

Thank you
Ayse

**Comment by ldenti** [comment]
Hi, from the log it seems you are using v1.0.5 (maybe from conda). But the README here on github is for v2... So the correct command to index is:
```
SVDSS index --fasta hs37d5.fa.gz --index hs37d5.fmd
```

Since this is creating more confusion than anything else, I'll update the conda package to v2.

**Comment by ldenti** [comment]
I drafted the official release (https://github.com/Parsoa/SVDSS/releases/tag/v2.0.0). With this new binary, you can use the command you were using and it should work. Let me know.

You can start using that binary or wait for the package to be updated in conda.

Best,

**Comment by ldenti** [comment]
SVDSS v2 is available in bioconda (https://anaconda.org/bioconda/svdss/files).

**Comment by aysegokce** [comment]
I confirm that it is working now! Thank you for the quick fix!

Best
Ayse
